version: "3"
services:
  postgis:
    image: postgis/postgis:9.5-2.5-alpine
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set!}
  rails:
    build:
      context: .
      args:
        - APP_DIR=${APP_DIR:?APP_DIR not set!}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"
    ports:
      - "3000:3000"
    depends_on:
      - postgis
    links:
      - "postgis:${DB_HOST:?DB_HOST not set!}"
